name: MinezoneCore
main: anthony.SuperCraftBrawl.Core
version: 1.0
commands:
   join:
      description: Join a game
      usage: /join [map name]
   hub:
      description: Hub command
   shop:
      description: Shop command
   l:
      description: Leave command
   cw:
      description: Crystal wars
   players:
      description: List of players in your game
   tournamentmodewithoutreset:
      description: Idk
   fav:
      description: Fav classes
   gamestats:
      description: Stats after a game
   list:
      description: List of online players
   leave:
      description: Leave the game you are currently in
   tournamentmodetoggle:
      description: Toggle Tournament
   class:
      description: Class command
   startgame:
      description: Start game
   setlevel:
      description: Set level command
   store:
      description: Store command
   nick:
      description: Nickname!
   tell:
      description: Msg command!
   setrank:
      description: Rank command!
      permission: scb.setrank
   setlives:
      description: Set lives command!
   online:
      description: Online players command!
   purchases:
      description: Purchases command!
   maps:
      description: Maps command!
   seen:
      description: Seen command
   ignite:
      description: Ignite a player!
   broadcast:
      description: Broadcast command
   msg:
      description: Message command
   rank:
      description: Ranks command
   spectate:
      description: Spectate command
   maplist:
      description: Displays list of SCB Maps
   socials:
      description: Socials
   vanish:
      description: Vanish
   unvanish:
      description: Unvanish
   gmc:
      description: Gamemode creative
   gms: 
      description: Gamemode survival
   gma:
      description: Gamemode adventure
   gmsp:
      description: Gamemode spectator
   gm:
      description: General gamemode command
   scbhelp:
      description: Displays SCB help/information
   dailyreward:
      description: Daily Rewards
   tutorial:
      description: Tutorial of the Server
   scb:
      description: Displays SCB help/information
   classes:
      description: Displays list of SCB Classes
   stats:
      description: Player Stats
   token:
      description: Give tokens
   cwm:
      description: Custom Win Messages!
   activegames:
      description: Test command
   help:
      description: HelpppppPPPppp!!!
   sc:
      description: Staff Chat
   staff:
      description: Staff command!
   rules:
      description: Displays the Server Rules
   parkour:
      description: Parkour
   invite:
      description: Invite command
   color:
      description: Color command
   tp:
      description: Teleport command
   world:
      description: World command
   punish:
      description: Punishment command
   exp:
      description: Exp command
   smmtest:
      description: SMM
   sh:
      description: Staff help command
   shr:
      description: Staff help reply command
   points:
      description: Points command
   give:
      description: Give command
   unmute:
      description: Unmute command
   fac:
      description: Test factions command
   sw:
      description: Skywars command
   kit:
      description: Kit command for SkyWars
      
permissions:
   scb.admin:
      description: Admin perms
      children:
         scb.developer: true
         scb.startGame: true
         scb.setLives: true
         scb.setrank: true
         scb.giveTokens: true
         scb.broadcast: true
         scb.ignite: true
         punish.networkban: true
   scb.developer:
      description: Developer perms
      children:
         scb.moderator: true
         scb.gm: true
         scb.gmc: true
         scb.gms: true
         scb.gmsp: true
         scb.gma: true
   
   scb.moderator:
      description: Moderator perms
      children:
         scb.trainee: true
         punish.ban: true
         punish.mute: true
   scb.senior_moderator:
      description: Moderator perms
      children:
         scb.trainee: true
         punish.ban: true
         punish.mute: true
   scb.trainee:
      description: Trainee perms
      children:
         scb.captain: true
         scb.vanish: true
         scb.unvanish: true
         scb.staffchat: true
         scb.staff: true
         scb.tp: true
         scb.staffhelp: true
         scb.staffhelpreply: true
         scb.anticheat: true
         minezone.2fa: true
         punish.gui: true
         punish.warning: true
         punish.check: true
         punish.kick: true
   scb.qa:
      description: Design perms
      children:
         scb.captain: true
   scb.media:
      description: Media perms
      children:
         scb.captain: true
   scb.captain:
      description: Captain perms
      children:
         scb.vip: true
         scb.customWin: true
         scb.wheat: true
         scb.invite: true
         scb.color: true
         scb.bypassQueue: true
         scb.customKillMsgs: true
         scb.winEffects: true
   scb.vip:
      description: Vip perms
      children:
         scb.default: true
         scb.nickname.use: true
         scb.bonusTokens: true
         scb.rankBonusOne: true
         scb.rankBonus: true
         scb.cooldown: true
         scb.chat: true
         scb.bypassFull: true
         scb.deathParticles: true
   scb.default:
      description: Default perms
      children:
         
   